// ============================================================
//  config.js — Centrale configuratie voor de lesregiekamer
// ============================================================

const LesConfig = {

    les: {
        titel: "Acceptatiecriteria",
        vak:   "Software Developer · MBO-4",
        duur:  45,
    },

    codes: {
        docent:       "DOC2025",
        lesoverzicht: "OVZ01",
        bughunt:      "BUG01",
        theorie:      "DOD01",
        tipsplit:     "TIP01",
        vergelijk:    "VRG01",
        exit:         "EXIT01",
    },

    fasen: [
        {
            id:          "bughunt",
            nummer:      "01",
            emoji:       "🎮",
            titel:       "Bug Hunt",
            omschrijving:"Speel het spel en ontdek wat niet klopt",
            werkvorm:    "Klassikaal",
            wvKlasse:    "wv-klassikaal",
            tijdLabel:   "0–5 min",
            duurMin:     5,
            url:         "pages/spel_bughunt.html",
            codeSleutel: "bughunt",
            kleur:       "#4facfe",
        },
        {
            id:          "lesoverzicht",
            nummer:      "02",
            emoji:       "🗺️",
            titel:       "Lesoverzicht & Leerdoelen",
            omschrijving:"Wat ga je vandaag leren?",
            werkvorm:    "Klassikaal",
            wvKlasse:    "wv-klassikaal",
            tijdLabel:   "5–8 min",
            duurMin:     3,
            url:         "pages/lesoverzicht.html",
            codeSleutel: "lesoverzicht",
            kleur:       "#00c07a",
        },
        {
            id:          "theorie",
            nummer:      "03",
            emoji:       "📖",
            titel:       "Theorie",
            omschrijving:"Wat zijn AC, waarom, hoe schrijf je ze",
            werkvorm:    "Klassikaal",
            wvKlasse:    "wv-klassikaal",
            tijdLabel:   "8–16 min",
            duurMin:     8,
            url:         "pages/theorie.html",
            codeSleutel: "theorie",
            kleur:       "#4facfe",
        },
        {
            id:          "tipsplit",
            nummer:      "04",
            emoji:       "🧮",
            titel:       "Opdracht: AC schrijven & testen",
            omschrijving:"TipSplit testen + eigen AC schrijven voor portfolio",
            werkvorm:    "4 Groepen",
            wvKlasse:    "wv-groepen",
            tijdLabel:   "16–32 min",
            duurMin:     16,
            url:         "pages/spel_tipsplit.html",
            codeSleutel: "tipsplit",
            kleur:       "#fbbf24",
        },
        {
            id:          "vergelijk",
            nummer:      "05",
            emoji:       "⚖️",
            titel:       "Nabespreking",
            omschrijving:"Vergelijken: met en zonder criteria — goede vs slechte criteria",
            werkvorm:    "Klassikaal",
            wvKlasse:    "wv-klassikaal",
            tijdLabel:   "32–42 min",
            duurMin:     10,
            url:         "pages/vergelijk.html",
            codeSleutel: "vergelijk",
            kleur:       "#ff6b35",
        },
        {
            id:          "exit",
            nummer:      "06",
            emoji:       "🏷️",
            titel:       "Afsluiting",
            omschrijving:"1 AC schrijven (exit ticket) · leerdoelen check · Canvas",
            werkvorm:    "Individueel",
            wvKlasse:    "wv-individueel",
            tijdLabel:   "42–45 min",
            duurMin:     3,
            url:         "pages/exitticket.html",
            codeSleutel: "exit",
            kleur:       "#00c07a",
        },
    ],
};
