// ============================================================
//  config.js — Centrale configuratie voor de lesregiekamer
// ============================================================

const LesConfig = {

    les: {
        titel: "Acceptatiecriteria",
        vak:   "Software Developer · MBO-4",
        duur:  45,
    },

    codes: {
        docent:       "DOC2025",
        bughunt:      "BUG01",
        lesoverzicht: "OVZ01",
        theorie:      "DOD01",
        schrijven:    "SCH01",
        testen:       "TES01",
        vergelijk:    "VRG01",
        exit:         "EXIT01",
    },

    fasen: [
        {
            id:          "bughunt",
            nummer:      "01",
            emoji:       "🎮",
            titel:       "1. Bug Hunt",
            omschrijving:"Speel het spel en ontdek wat niet klopt",
            werkvorm:    "Klassikaal",
            wvKlasse:    "wv-klassikaal",
            tijdLabel:   "0–5 min",
            duurMin:     5,
            url:         "pages/spel_bughunt.html",
            codeSleutel: "bughunt",
            kleur:       "#4facfe",
        },
        {
            id:          "lesoverzicht",
            nummer:      "02",
            emoji:       "🗺️",
            titel:       "Lesoverzicht",  // geen nummer — extra tegel
            omschrijving:"Wat ga je vandaag leren?",
            werkvorm:    "Klassikaal",
            wvKlasse:    "wv-klassikaal",
            tijdLabel:   "5–8 min",
            duurMin:     3,
            url:         "pages/lesoverzicht.html",
            codeSleutel: "lesoverzicht",
            kleur:       "#00c07a",
        },
        {
            id:          "theorie",
            nummer:      "03",
            emoji:       "📖",
            titel:       "2. Theorie",
            omschrijving:"Wat zijn AC, waarom, hoe schrijf je ze",
            werkvorm:    "Klassikaal",
            wvKlasse:    "wv-klassikaal",
            tijdLabel:   "8–16 min",
            duurMin:     8,
            url:         "pages/theorie.html",
            codeSleutel: "theorie",
            kleur:       "#4facfe",
        },
        {
            id:          "schrijven",
            nummer:      "04",
            emoji:       "✍️",
            titel:       "3. Opdracht 1: AC schrijven",
            omschrijving:"Schrijf acceptatiecriteria voor TipSplit",
            werkvorm:    "Tweetallen / individueel",
            wvKlasse:    "wv-groepen",
            tijdLabel:   "16–25 min",
            duurMin:     9,
            url:         "pages/opdracht-schrijven.html",
            codeSleutel: "schrijven",
            kleur:       "#a78bfa",
        },
        {
            id:          "testen",
            nummer:      "05",
            emoji:       "🧮",
            titel:       "4. Opdracht 2: AC testen",
            omschrijving:"Test jullie acceptatiecriteria in TipSplit",
            werkvorm:    "Tweetallen / individueel",
            wvKlasse:    "wv-groepen",
            tijdLabel:   "25–35 min",
            duurMin:     10,
            url:         "pages/opdracht-testen.html",
            codeSleutel: "testen",
            kleur:       "#fbbf24",
        },
        {
            id:          "vergelijk",
            nummer:      "06",
            emoji:       "⚖️",
            titel:       "5. Nabespreking",
            omschrijving:"Vergelijken: goede vs slechte criteria",
            werkvorm:    "Klassikaal",
            wvKlasse:    "wv-klassikaal",
            tijdLabel:   "35–43 min",
            duurMin:     8,
            url:         "pages/vergelijk.html",
            codeSleutel: "vergelijk",
            kleur:       "#ff6b35",
        },
        {
            id:          "exit",
            nummer:      "07",
            emoji:       "🏷️",
            titel:       "6. Afsluiting",
            omschrijving:"Schrijf individueel 1 AC voor je portfolio. Benoem wat een goed criterium maakt.",
            werkvorm:    "Individueel",
            wvKlasse:    "wv-individueel",
            tijdLabel:   "43–45 min",
            duurMin:     2,
            url:         "pages/exitticket.html",
            codeSleutel: "exit",
            kleur:       "#00c07a",
        },
    ],
};
